In [19]:
from openbb_terminal.sdk import openbb
import quantstats as qs
qs.extend_pandas()
import pandas as pd

In [8]:
#load data from openBB, single stock load from stocks module
# data_spy = openbb.stocks.load("JPM", start_date="2023-02-06", end_date="2023-02-09")
# data_spy

Loading Daily data for JPM with starting period 2023-02-06.

,Open,High,Low,Close,Adj Close,Volume
date,,,,,,
2023-02-06,140.229996,142.240005,140.029999,141.919998,141.919998,8406200
2023-02-07,141.380005,144.339996,141.179993,143.649994,143.649994,10447900
2023-02-08,142.649994,144.039993,142.279999,142.639999,142.639999,6958000

In [12]:
start = '2013-02-13'
end = '2023-02-13'

symbols = ["SPY", "COST", "AVGO", "APD", "AMGN", "CVX", "AAPL", "DIS",
          "BAC", "GS", "SBUX", "COF", "ETN", "XOM", "HD", "MA",
          "QQQ", "IWM", "JNJ", "JPM", "MCD", "MRK", "MSFT", "NVDA", "NKE",
          "PEP", "PFE", "PG", "MO", "BUD", "SHW", "TSCO", "UNH", "VZ", "V", "WMT"]

data = openbb.economy.index(symbols, start_date=start, end_date=end) #.economy.index pulls close price
data

,SPY,COST,AVGO,APD,AMGN,CVX,AAPL,DIS,BAC,GS,...,PFE,PG,MO,BUD,SHW,TSCO,UNH,VZ,V,WMT
Date,,,,,,,,,,,,,,,,,,,,,
2013-02-13 00:00:00-05:00,126.366096,83.569160,26.767317,64.430939,65.928307,76.993698,14.405273,49.963749,10.341106,130.554367,...,17.901686,57.207523,19.707800,68.738297,50.024681,45.482628,49.074028,28.145342,36.090050,57.176167
2013-02-14 00:00:00-05:00,126.482368,83.889870,27.125032,64.365669,65.757576,77.113663,14.392323,49.891014,10.307119,131.745682,...,17.941460,57.371910,19.328148,72.242958,49.486500,45.769379,48.919659,28.025219,36.372208,56.719639
2013-02-15 00:00:00-05:00,126.332932,84.013176,26.744486,64.031799,64.896004,76.613853,14.193983,50.554661,10.222143,130.951431,...,18.093962,57.192577,19.481142,72.219597,50.402615,45.778187,49.151203,28.069487,36.840919,55.502277
2013-02-19 00:00:00-05:00,127.279663,83.791183,27.048920,64.372917,65.299599,77.253616,14.188739,50.663746,10.358097,134.043762,...,18.372433,57.820248,19.702129,72.499985,49.616493,45.632607,48.585255,28.132708,36.752300,55.069790
2013-02-20 00:00:00-05:00,125.693375,83.116898,26.386782,63.581856,65.703224,76.633827,13.845122,49.636467,10.026710,131.111969,...,18.279608,57.596062,19.770126,72.328651,48.174248,44.803249,47.341908,28.398222,36.241634,55.430202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-06 00:00:00-05:00,409.829987,515.590027,601.299988,283.029999,243.850006,169.639999,151.498688,109.870003,36.369999,370.799988,...,43.759998,141.399994,46.959999,58.730000,243.029999,232.419998,475.239990,41.279999,228.991501,140.679993
2023-02-07 00:00:00-05:00,415.190002,516.530029,614.450012,285.070007,244.000000,174.089996,154.414230,111.629997,36.770000,374.399994,...,43.590000,140.020004,46.560001,58.419998,238.440002,232.729996,476.880005,40.549999,230.867828,140.979996
2023-02-08 00:00:00-05:00,410.649994,503.809998,601.710022,287.239990,240.199997,170.000000,151.688400,111.779999,36.500000,375.100006,...,43.980000,138.570007,46.500000,58.200001,235.509995,231.240005,483.220001,40.520000,229.750000,140.220001
2023-02-09 00:00:00-05:00,407.089996,500.630005,599.409973,286.890015,240.000000,168.440002,150.639999,110.360001,35.720001,367.989990,...,43.340000,137.050003,46.330002,58.080002,231.509995,233.759995,485.730011,39.810001,229.350006,141.520004
2023-02-10 00:00:00-05:00,408.040009,499.989990,593.250000,287.820007,242.500000,171.970001,151.009995,108.059998,35.580002,371.279999,...,43.880001,138.259995,47.240002,58.049999,230.490005,233.000000,494.250000,40.009998,227.199997,143.720001

In [31]:
data["Date"] = pd.to_datetime(data.index).date
data = data.set_index("Date")
data

,SPY,COST,AVGO,APD,AMGN,CVX,AAPL,DIS,BAC,GS,...,PG,MO,BUD,SHW,TSCO,UNH,VZ,V,WMT,Date_new
Date,,,,,,,,,,,,,,,,,,,,,
2013-02-13,126.366096,83.569160,26.767317,64.430939,65.928307,76.993698,14.405273,49.963749,10.341106,130.554367,...,57.207523,19.707800,68.738297,50.024681,45.482628,49.074028,28.145342,36.090050,57.176167,2013-02-13
2013-02-14,126.482368,83.889870,27.125032,64.365669,65.757576,77.113663,14.392323,49.891014,10.307119,131.745682,...,57.371910,19.328148,72.242958,49.486500,45.769379,48.919659,28.025219,36.372208,56.719639,2013-02-14
2013-02-15,126.332932,84.013176,26.744486,64.031799,64.896004,76.613853,14.193983,50.554661,10.222143,130.951431,...,57.192577,19.481142,72.219597,50.402615,45.778187,49.151203,28.069487,36.840919,55.502277,2013-02-15
2013-02-19,127.279663,83.791183,27.048920,64.372917,65.299599,77.253616,14.188739,50.663746,10.358097,134.043762,...,57.820248,19.702129,72.499985,49.616493,45.632607,48.585255,28.132708,36.752300,55.069790,2013-02-19
2013-02-20,125.693375,83.116898,26.386782,63.581856,65.703224,76.633827,13.845122,49.636467,10.026710,131.111969,...,57.596062,19.770126,72.328651,48.174248,44.803249,47.341908,28.398222,36.241634,55.430202,2013-02-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-06,409.829987,515.590027,601.299988,283.029999,243.850006,169.639999,151.498688,109.870003,36.369999,370.799988,...,141.399994,46.959999,58.730000,243.029999,232.419998,475.239990,41.279999,228.991501,140.679993,2023-02-06
2023-02-07,415.190002,516.530029,614.450012,285.070007,244.000000,174.089996,154.414230,111.629997,36.770000,374.399994,...,140.020004,46.560001,58.419998,238.440002,232.729996,476.880005,40.549999,230.867828,140.979996,2023-02-07
2023-02-08,410.649994,503.809998,601.710022,287.239990,240.199997,170.000000,151.688400,111.779999,36.500000,375.100006,...,138.570007,46.500000,58.200001,235.509995,231.240005,483.220001,40.520000,229.750000,140.220001,2023-02-08
2023-02-09,407.089996,500.630005,599.409973,286.890015,240.000000,168.440002,150.639999,110.360001,35.720001,367.989990,...,137.050003,46.330002,58.080002,231.509995,233.759995,485.730011,39.810001,229.350006,141.520004,2023-02-09
2023-02-10,408.040009,499.989990,593.250000,287.820007,242.500000,171.970001,151.009995,108.059998,35.580002,371.279999,...,138.259995,47.240002,58.049999,230.490005,233.000000,494.250000,40.009998,227.199997,143.720001,2023-02-10

In [32]:
spy_returns = data["SPY"].pct_change()
spy_returns

Date
2013-02-13         NaN
2013-02-14    0.000920
2013-02-15   -0.001181
2013-02-19    0.007494
2013-02-20   -0.012463
                ...
2023-02-06   -0.006111
2023-02-07    0.013079
2023-02-08   -0.010935
2023-02-09   -0.008669
2023-02-10    0.002334
Name: SPY, Length: 2517, dtype: float64

In [33]:
cost_returns = data["COST"].pct_change()
avgo_returns = data["AVGO"].pct_change()
apd_returns = data["APD"].pct_change()
amgn_returns = data["AMGN"].pct_change()
cvx_returns = data["CVX"].pct_change()
aapl_returns = data["AAPL"].pct_change()
dis_returns = data["DIS"].pct_change()
bac_returns = data["BAC"].pct_change()
gs_returns = data["GS"].pct_change()
sbux_returns = data["SBUX"].pct_change()
cof_returns = data["COF"].pct_change()
etn_returns = data["ETN"].pct_change()
xom_returns = data["XOM"].pct_change()
hd_returns = data["HD"].pct_change()
ma_returns = data["MA"].pct_change()
qqq_returns = data["QQQ"].pct_change()
iwm_returns = data["IWM"].pct_change()
jnj_returns = data["JNJ"].pct_change()
jpm_returns = data["JPM"].pct_change()
mcd_returns = data["MCD"].pct_change()
mrk_returns = data["MRK"].pct_change()
msft_returns = data["MSFT"].pct_change()
nvda_returns = data["NVDA"].pct_change()
nke_returns = data["NKE"].pct_change()
pep_returns = data["PEP"].pct_change()
pfe_returns = data["PFE"].pct_change()
pg_returns = data["PG"].pct_change()
mo_returns = data["MO"].pct_change()
bud_returns = data["BUD"].pct_change()
shw_returns = data["SHW"].pct_change()
tsco_returns = data["TSCO"].pct_change()
unh_returns = data["UNH"].pct_change()
vz_returns = data["VZ"].pct_change()
v_returns = data["V"].pct_change()
wmt_returns = data["WMT"].pct_change()

In [34]:
#data check
gs_returns

Date
2013-02-13         NaN
2013-02-14    0.009125
2013-02-15   -0.006029
2013-02-19    0.023614
2013-02-20   -0.021872
                ...
2023-02-06    0.002298
2023-02-07    0.009709
2023-02-08    0.001870
2023-02-09   -0.018955
2023-02-10    0.008940
Name: GS, Length: 2517, dtype: float64

In [35]:
#weight the portfolio (0.0285 = equal wt for 35 stocks)
#weight the portfolio
portfolio = (
    (cost_returns* .0059) + (avgo_returns*.0088) + (apd_returns*.0066) + (amgn_returns*.0029) + (cvx_returns*.0191) + 
    (aapl_returns* .0125) + (dis_returns*.1366) + (bac_returns*.1109) + (gs_returns*.0044) + (sbux_returns*.0389) + 
    (cof_returns* .0132) + (etn_returns*.0264) + (xom_returns*.0345) + (hd_returns*.0066) + (ma_returns*.0125) +
    (qqq_returns* .0800) + (iwm_returns*.0352) + (jnj_returns*.0184) + (jpm_returns*.0228) + (mcd_returns*.0330) + 
    (mrk_returns* .0081) + (msft_returns*.0213) + (nvda_returns*.1043) + (nke_returns*.0264) + (pep_returns*.0110) + 
    (pfe_returns* .0404) + (pg_returns*.0125) + (mo_returns*.0162) + (bud_returns*.0360) + (shw_returns*.0073) + 
    (tsco_returns* .0492) + (unh_returns*.0066) + (vz_returns*.0235) + (v_returns*.0081) + (wmt_returns*.0132)
                )
portfolio.head()

Date
2013-02-13         NaN
2013-02-14    0.004757
2013-02-15   -0.000332
2013-02-19    0.003672
2013-02-20   -0.014489
dtype: float64

In [36]:
#metrics for the weighted portfolio vs spy(benchmark)
qs.reports.metrics(portfolio, spy_returns, mode="full")

AttributeError: Can only use .dt accessor with datetimelike values